---
fontsize: 11pt
geometry: margin=.5in
header-includes:
   - \setlength\parindent{24pt}
   - \usepackage{caption}
   - \usepackage{tipa}
   - \usepackage{array}
output: pdf_document
---

\pagenumbering{gobble}

## 1. Descripción articulatoria (30 puntos).

\begin{center}
\begin{tabular}{|m{4cm}|m{4cm}|m{4cm}|m{4cm}|}
\hline 
Fonema                     & Modo                             & Punto                            & Sonoridad       \\
\hline
\textipa{/a/}              & \phantom{hello worldhello world} & \phantom{hello worldhello world} & \phantom{hello worldhello world} \\
\hline 
\textipa{/\texttheta/}     &                                  &                                  & \\ [2ex]
\hline
\textipa{/d/}              &                                  &                                  & \\ [2ex]
\hline
\textipa{/i/}              &                                  &                                  & \\ [2ex]
\hline
\textipa{/\textltailn/}    &                                  &                                  & \\ [2ex]
\hline
\textipa{/l/}              &                                  &                                  & \\ [2ex]
\hline
\textipa{/\textfishhookr/} &                                  &                                  & \\ [2ex]
\hline
\textipa{/\textteshlig/}   &                                  &                                  & \\ [2ex]
\hline
\textipa{/\textctj/}       &                                  &                                  & \\ [2ex]
\hline
\textipa{/u/}              &                                  &                                  & \\ [2ex]
\hline
\end{tabular}
\end{center}


\vspace{.75in}

## 1. Descripción articulatoria (30 puntos).

\begin{center}
\begin{tabular}{|m{4cm}|m{4cm}|m{4cm}|m{4cm}|}
\hline 
Fonema                     & Modo                             & Punto                            & Sonoridad       \\
\hline
\textipa{/a/}              & \phantom{hello worldhello world} & \phantom{hello worldhello world} & \phantom{hello worldhello world} \\
\hline 
\textipa{/\texttheta/}     &                                  &                                  & \\ [2ex]
\hline
\textipa{/d/}              &                                  &                                  & \\ [2ex]
\hline
\textipa{/i/}              &                                  &                                  & \\ [2ex]
\hline
\textipa{/\textltailn/}    &                                  &                                  & \\ [2ex]
\hline
\textipa{/l/}              &                                  &                                  & \\ [2ex]
\hline
\textipa{/\textfishhookr/} &                                  &                                  & \\ [2ex]
\hline
\textipa{/\textteshlig/}   &                                  &                                  & \\ [2ex]
\hline
\textipa{/\textctj/}       &                                  &                                  & \\ [2ex]
\hline
\textipa{/u/}              &                                  &                                  & \\ [2ex]
\hline
\end{tabular}
\end{center}










